"""Update models after merge

Revision ID: 53170a59cfae
Revises: 3380f41284da
Create Date: 2025-12-14 20:29:52.730035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53170a59cfae'
down_revision: Union[str, None] = '3380f41284da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlists')
    op.alter_column('products', 'gender',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Unisex'::character varying"))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_product_embedding_clip_hnsw', 'products', ['embedding_clip'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 128}, postgresql_ops={'embedding_clip': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_product_embedding_clip_lower_hnsw', 'products', ['embedding_clip_lower'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 128}, postgresql_ops={'embedding_clip_lower': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_product_embedding_clip_upper_hnsw', 'products', ['embedding_clip_upper'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 128}, postgresql_ops={'embedding_clip_upper': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_product_embedding_hnsw', 'products', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 128}, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_gender'), 'products', ['gender'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.add_column('users', sa.Column('detail_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'detail_address')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_gender'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('ix_product_embedding_hnsw', table_name='products', postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 128}, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_product_embedding_clip_upper_hnsw', table_name='products', postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 128}, postgresql_ops={'embedding_clip_upper': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_product_embedding_clip_lower_hnsw', table_name='products', postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 128}, postgresql_ops={'embedding_clip_lower': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_product_embedding_clip_hnsw', table_name='products', postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 128}, postgresql_ops={'embedding_clip': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Unisex'::character varying"))
    op.create_table('wishlists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='wishlists_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlists_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wishlists_pkey'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_wishlist_user_product')
    )
    # ### end Alembic commands ###
